# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google
    search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "mamananama.github.io"
url: "https://mamananama.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mamananama
plugins:
    - jekyll-feed

permalink: "categories/:categories/:slug:output_ext"
paginate: 10
pagenate_path: "categories/:categories"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

excerpt_seperator: <!--break-->

collections:
    posts:
        output: true
        sort_by: date

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  hard_wrap: false

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "Rakefile"
  - "script/"
  - "*.log"
  - ".sass-cache/"
  - ".jekyll-cache/"
  - ".bundle/"
  - ".vscode/"
  - ".idea/"
  - "*.iml"
  - "*.sublime-*"
  - "*.swp"
  - "*.swo"
  - ".DS_Store"
  - "Thumbs.db"
  - "desktop.ini"
  - "*.bak"
  - "*.tmp"
  - "*.temp"
  - "*.less"
  - "*.coffee"
  - ".github/*"
  - ".history/*"
  - "_config.yml"
  - ".gitignore"
  - "frontmatter.json"



tipue_search:
    include:
        pages: false
        collections: [posts]
    exclude:
        files: [search.html, index.html, tags.html, "*.md", "*.css", "*.scss", "*.js", "*.json", "*.xml", "*.rb", "assets/*", "_layouts/*"]
        categories: []
        tags: []

# 한글 URL 처리를 위한 설정
encoding: UTF-8
permalink_style: pretty
